# Generated by Django 4.2.7 on 2024-10-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_labels_todo_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
