# Generated by Django 4.2.7 on 2024-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_rename_labels_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='label',
        ),
        migrations.AddField(
            model_name='todo',
            name='labels',
            field=models.ManyToManyField(related_name='todos', to='Todo.label'),
        ),
    ]
