# Generated by Django 4.2.7 on 2024-10-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_remove_todo_label_todo_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='todos', to='Todo.label'),
        ),
    ]
