# Generated by Django 4.2.7 on 2025-06-11 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Todo', '0008_todo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
